language: php
php:
  - 5.4
#services:
#  - mysql

#before_script:
#  - sudo apt-get install apache2 libapache2-mod-fastcgi
#  # enable php-fpm
#  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
#  - sudo a2enmod rewrite actions fastcgi alias
#  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
#  # configure apache virtual hosts
#  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
#  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
#  - sudo service apache2 restart
#
#  - rm -R vendor/
#  - rm composer.lock
#  - ./composer.phar install
#  # db setup
#  - mysql < ./sql/carona_certa.sql

script:
  - echo "Building"
#  - npm test
  - php composer.phar install
  - npm install -g apidoc
  - npm run -script docs

before_deploy:
  - git config --global user.email "bot@travis-ci.com"
  - git config --global user.name "Bot - Travis CI"
  - git checkout $TRAVIS_BRANCH
  - git add -f vendor
  - git commit -am "Build: $TRAVIS_BUILD_NUMBER"

deploy:
  provider: openshift
  user: rodrigoegoncalves@gmail.com
  password:
    secure: G+jDwdA5uAEoshon3+JIvGB886+TJAFT1HEf1LM3c08q6FMwJATYshwQ4EdwWvEMmKg09yB1Uzk0CZgtHYdJueOYCTNv7Q/eTb5m1PTTkUJJFUUd44bXBlnEYasxPohfalCYxeprZkAEkN3yjd4neCiwDDcLDFO+umxGHjnWw6U=
  app:
    master: caronacerta
  domain: rodrigoeg
  skip_cleanup: true

branches:
  only:
    - master