language: php
php:
  - 5.4
services:
  - mysql

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl

  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

  - rm -R vendor/
  - rm composer.lock
  - ./composer.phar install
  # db setup
  - mysql < ./sql/carona_certa.sql

script:
  - echo "Building"
  - ./bin/behat

deploy:
  provider: openshift
  user: rodrigoegoncalves@gmail.com
  password:
    secure: G+jDwdA5uAEoshon3+JIvGB886+TJAFT1HEf1LM3c08q6FMwJATYshwQ4EdwWvEMmKg09yB1Uzk0CZgtHYdJueOYCTNv7Q/eTb5m1PTTkUJJFUUd44bXBlnEYasxPohfalCYxeprZkAEkN3yjd4neCiwDDcLDFO+umxGHjnWw6U=
  app:
    master: caronacerta
  domain: rodrigoeg

branches:
  only:
    - master