language: php
php:
  - 5.4
services:
  - mysql

before_script:
  - rm -R vendor/
  - rm composer.lock
  - ./composer.phar install
  # db setup
  - mysql < ./sql/carona_certa.sql

script:
  - echo "Building"
  - ./bin/behat

deploy:
  provider: openshift
  user: rodrigoegoncalves@gmail.com
  password:
    secure: G+jDwdA5uAEoshon3+JIvGB886+TJAFT1HEf1LM3c08q6FMwJATYshwQ4EdwWvEMmKg09yB1Uzk0CZgtHYdJueOYCTNv7Q/eTb5m1PTTkUJJFUUd44bXBlnEYasxPohfalCYxeprZkAEkN3yjd4neCiwDDcLDFO+umxGHjnWw6U=
  app:
    master: caronacerta
  domain: rodrigoeg

branches:
  only:
    - master