<?php
/**
 * Database configuration
 */

$OPENSHIFT_MYSQL_DB_USERNAME = getenv('OPENSHIFT_MYSQL_DB_USERNAME');
$OPENSHIFT_MYSQL_DB_PASSWORD = getenv('OPENSHIFT_MYSQL_DB_PASSWORD');
$OPENSHIFT_MYSQL_DB_HOST = getenv('OPENSHIFT_MYSQL_DB_HOST');
$OPENSHIFT_MYSQL_DB_PORT = getenv('OPENSHIFT_MYSQL_DB_PORT');

define('DB_USERNAME', ($OPENSHIFT_MYSQL_DB_USERNAME) ? $OPENSHIFT_MYSQL_DB_USERNAME : 'root');
define('DB_PASSWORD', ($OPENSHIFT_MYSQL_DB_PASSWORD) ? $OPENSHIFT_MYSQL_DB_PASSWORD : '');
define('DB_HOST', ($OPENSHIFT_MYSQL_DB_HOST) ? $OPENSHIFT_MYSQL_DB_HOST : 'localhost');
define('DB_NAME', 'task_manager');
define('DB_PORT', ($OPENSHIFT_MYSQL_DB_PORT) ? $OPENSHIFT_MYSQL_DB_PORT : 3306);

define('USER_CREATED_SUCCESSFULLY', 0);
define('USER_CREATE_FAILED', 1);
define('USER_ALREADY_EXISTS', 2);
